apiVersion: v1
kind: Service
metadata:
  name: flask-service 
  namespace: monitoring
  labels:
    app: flask
spec:
  selector:
    app: flask
  ports:      
  - name: http
    port: 5000
    targetPort: 5000
  type: ClusterIP
