apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flaskapi-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring 
spec:
  selector:
    matchLabels:
      app: flask
  endpoints:
  - port: http
    path: /metrics
    interval: 15s